version: 2

sources:
  - name: bronze
    database: postgres
    schema: bronze
    tables:
      - name: game
        description: "{{ doc('game') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: id
            description: "A unique identifier for each game."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: genre_id
            description: "The ID linking the game to its genre in the genre table."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','genre')
                  field: id
              - not_null

          - name: game_name
            description: "The full name of the game."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - not_null
      
      - name: game_platform
        description: "{{ doc('game_platform') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 4
        columns:
          - name: id
            description: "A unique identifier for each record in the game_platform table."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: game_publisher_id
            description: "The ID linking the record to the game_publisher table."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','game_publisher')
                  field: id
              - not_null
          
          - name: platform_id
            description: "The ID linking the record to the platform table."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','platform')
                  field: id
              - not_null

          - name: release_year
            description: "The year the game was released on the specified platform."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - not_null
      
      - name: game_publisher
        description: "{{ doc('game_publisher') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: id
            description: "A unique identifier for each record in the game_publisher table."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: game_id
            description: "The ID linking the record to the games table."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','game')
                  field: id
              - not_null
          
          - name: publisher_id
            description: "The ID linking the record to the publisher table."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','publisher')
                  field: id
              - not_null
      
      - name: genre
        description: "{{ doc('genre') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            description: "A unique identifier for each genre."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: genre_name
            description: "The name of the genre."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - not_null
      
      - name: platform
        description: "{{ doc('genre') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            description: "A unique identifier for each platform."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: platform_name
            description: 'The name of the platform, such as "PS3," "PS," "3DS," etc.'
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - dbt_expectations.expect_column_values_to_be_in_set:
                  value_set: ['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA', '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC', 'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16', '3DO', 'GG', 'PCFX']
              - not_null
      
      - name: publisher
        description: "{{ doc('publisher') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            description: "A unique identifier for each publisher."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: publisher_name
            description: 'The name of the publisher, such as "1C Company," "Aerosoft," etc.'
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - not_null
      
      - name: region
        description: "{{ doc('region') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            description: "A unique identifier for each region."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: region_name
            description: 'The name of the region, such as "North America," "Europe," etc.'
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - not_null
      
      - name: region_sales
        description: "{{ doc('region_sales') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: region_id
            description: "The ID linking the record to the region table, identifying the region where the sales occurred."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','region')
                  field: id
              - not_null
          
          - name: game_platform_id
            description: "The ID linking the record to the game_platform table, identifying the platform on which the game was sold."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','game_platform')
                  field: id
              - not_null

          - name: num_sales
            description: "The number of sales recorded for the specific region and platform."
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: NUMERIC
              - not_null