version: 2

sources:
  - name: bronze
    database: postgres
    schema: bronze
    tables:
      - name: game
        description: "{{ doc('game') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: genre_id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','genre')
                  field: id
              - not_null

          - name: game_name
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - not_null
      
      - name: game_platform
        description: "{{ doc('game_platform') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 4
        columns:
          - name: id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: game_publisher_id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','game_publisher')
                  field: id
              - not_null
          
          - name: platform_id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','platform')
                  field: id
              - not_null

          - name: release_year
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - not_null
      
      - name: game_publisher
        description: "{{ doc('game_publisher') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: game_id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','game')
                  field: id
              - not_null
          
          - name: publisher_id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','publisher')
                  field: id
              - not_null
      
      - name: genre
        description: "{{ doc('genre') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: genre_name
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - unique
              - not_null
      
      - name: platform
        description: "{{ doc('platform') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: platform_name
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - unique
              - not_null
      
      - name: publisher
        description: "{{ doc('publisher') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: publisher_name
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - unique
              - not_null
      
      - name: region
        description: "{{ doc('region') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 2
        columns:
          - name: id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - unique
              - not_null
          
          - name: region_name
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: CHARACTER VARYING
              - unique
              - not_null
      
      - name: region_sales
        description: "{{ doc('region_sales') }}"
        data_tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: region_id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','region')
                  field: id
              - not_null
          
          - name: game_platform_id
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: INTEGER
              - relationships:
                  to: source('bronze','game_platform')
                  field: id
              - not_null

          - name: num_sales
            data_tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: NUMERIC
              - not_null